services:
  instance:
    container_name: instance
    restart: always
    build:
      context: .
      dockerfile: packages/container/instance/docker/Containerfile
    environment:
      INSTANCE_ID: ${INSTANCE_ID}
      INSTANCE_ROOT: /crackodata/instances
      WORDLIST_ROOT: /crackodata/wordlists
    user: 0:0
    networks:
      - crackosaurus-app
    volumes:
      - crackosaurus-instances:/crackodata/instances
      - crackosaurus-wordlists:/crackodata/wordlists

networks:
  crackosaurus-app:
    external: true

volumes:
  crackosaurus-instances:
    external: true
  crackosaurus-wordlists:
    external: true